<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rooms daily report – {{ $hotel->name }}</title>
    <style>
        @media print {
            @page { size: A4; margin: 15mm; }
            body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
        }
        body { font-family: sans-serif; font-size: 10.5px; color: #333; max-width: 210mm; margin: 0 auto; padding: 10px; }
        .header { border-bottom: 1px solid #ddd; padding-bottom: 10px; margin-bottom: 12px; }
        .header .contacts { color: #555; font-size: 10px; line-height: 1.5; margin-top: 8px; width: 100%; }
        .header .contacts > div { margin-top: 4px; }
        .header .contacts > div:first-child { margin-top: 0; }
        .header .contacts strong { color: #111; font-weight: 700; }
        .header .contacts .address { white-space: pre-line; }
        .report-title { font-size: 12px; font-weight: 700; margin-bottom: 6px; }
        .report-meta { color: #666; margin-bottom: 10px; font-size: 10px; line-height: 1.5; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ddd; padding: 4px 5px; text-align: left; vertical-align: top; }
        th { background: #f5f5f5; font-weight: 600; }
        .text-end { text-align: right; }
        .muted { color: #666; }
        .signature-block { margin-top: 28px; display: flex; justify-content: space-between; gap: 28px; page-break-inside: avoid; flex-wrap: wrap; }
        .sig-col { flex: 1 1 30%; font-size: 10px; }
        .sig-col .sig-heading { font-weight: 700; margin-bottom: 12px; font-size: 11px; }
        .sig-field { margin-bottom: 16px; }
        .sig-field .sig-label { color: #555; margin-bottom: 4px; }
        .sig-field .sig-line { border-bottom: 1px solid #333; min-height: 26px; }
        .totals { margin-top: 10px; }
        .summary-grid { display: flex; flex-wrap: wrap; gap: 12px; margin-top: 12px; }
        .summary-box { flex: 1 1 200px; border: 1px solid #ddd; padding: 8px; font-size: 10px; }
        .summary-box strong { display: block; margin-bottom: 4px; }
    </style>
</head>
<body>
    <div class="header">
        <x-hotel-document-header :hotel="$hotel">
            <div class="contacts">
                @if(filled($hotel->address))
                    <div class="address"><strong>{{ __('Address') }}:</strong> {{ $hotel->address }}</div>
                @endif
                @if(filled($hotel->contact))
                    <div><strong>{{ __('Phone') }}:</strong> {{ $hotel->contact }}</div>
                @endif
                @if(filled($hotel->reservation_phone) && $hotel->reservation_phone !== $hotel->contact)
                    <div><strong>{{ __('Reservations') }}:</strong> {{ $hotel->reservation_phone }}</div>
                @endif
                @if(filled($hotel->email))
                    <div><strong>{{ __('Email') }}:</strong> {{ $hotel->email }}</div>
                @endif
                @if(filled($hotel->fax))
                    <div><strong>{{ __('Fax') }}:</strong> {{ $hotel->fax }}</div>
                @endif
                @if(! filled($hotel->contact) && ! filled($hotel->email) && ! filled($hotel->address) && ! filled($hotel->reservation_phone) && ! filled($hotel->fax))
                    @if(filled($hotel->reservation_contacts))
                        <div class="address"><strong>{{ __('Contact') }}:</strong> {{ $hotel->reservation_contacts }}</div>
                    @endif
                @endif
            </div>
        </x-hotel-document-header>
    </div>

    <div class="report-title">Rooms daily report <span class="muted" style="font-weight:400;">(accommodation / folios only)</span></div>
    <div class="report-meta">
        <div><strong>Date retrieved:</strong> {{ $retrievedAt }}</div>
        <div><strong>Generated by:</strong> {{ $generatedBy->name }}</div>
        <div><strong>Report period:</strong> {{ $date }}</div>
    </div>

    @if(count($rows) > 0)
        <div class="summary-grid" style="margin-bottom: 12px;">
            <div class="summary-box">
                <strong>Total sales (period)</strong>
                <div>{{ $currency }} {{ number_format((float) $totalGross, 2, '.', '') }}</div>
                <span class="muted">In-house accommodation, day-share of folio totals.</span>
            </div>
            <div class="summary-box">
                <strong>Paid amount (period)</strong>
                <div>{{ $currency }} {{ number_format((float) ($totalPaidPeriod ?? 0), 2, '.', '') }}</div>
                <span class="muted">Reservation payments recorded (matches breakdown below).</span>
            </div>
            <div class="summary-box">
                <strong>Balance</strong>
                <div>{{ $currency }} {{ number_format((float) $totalBalanceDue, 2, '.', '') }}</div>
                <span class="muted">Outstanding folios; each guest once.</span>
            </div>
        </div>

        @if($reportsShowVat ?? false)
            <p class="muted" style="margin: 0 0 10px 0;"><strong>VAT (period):</strong> {{ $currency }} {{ number_format((float) $totalTax, 2, '.', '') }}</p>
        @endif

        <div class="summary-grid" style="margin-bottom: 12px;">
            <div class="summary-box" style="flex: 1 1 100%;">
                <strong>Room / folio payments by type (period)</strong>
                @foreach($paymentsByType ?? [] as $key => $amt)
                    <div>{{ ($paymentTypeLabels[$key] ?? $key) }}: <span class="text-end" style="float:right;">{{ $currency }} {{ number_format((float) $amt, 2, '.', '') }}</span></div>
                @endforeach
            </div>
        </div>

        <table>
            <thead>
            <tr>
                <th style="white-space: nowrap;">Date</th>
                <th>Guest</th>
                <th>Address</th>
                <th>ID</th>
                <th>Phone</th>
                <th>Room</th>
                <th class="text-end">Nights</th>
                <th class="text-end">Room rate</th>
                <th>Payment mode</th>
                <th class="text-end">Paid</th>
                <th class="text-end">Credit</th>
                <th class="text-end">Balance</th>
                @if($reportsShowVat ?? false)
                    <th class="text-end">VAT day</th>
                @endif
            </tr>
            </thead>
            <tbody>
            @foreach($rows as $row)
                <tr>
                    <td class="muted">{{ $row['date'] }}</td>
                    <td><strong>{{ $row['guest_name'] }}</strong></td>
                    <td>{{ $row['guest_address'] }}</td>
                    <td>{{ $row['guest_id_number'] }}</td>
                    <td>{{ $row['guest_phone'] }}</td>
                    <td>{{ $row['room_number'] }}</td>
                    <td class="text-end">{{ (int) ($row['nights'] ?? 0) }}</td>
                    <td class="text-end">{{ $row['currency'] }} {{ $row['room_rate'] }}</td>
                    <td>{{ $row['payment_mode'] }}</td>
                    <td class="text-end">{{ $row['currency'] }} {{ $row['paid_today'] }}</td>
                    <td class="text-end">{{ $row['currency'] }} {{ $row['credit_today'] }}</td>
                    <td class="text-end">{{ $row['currency'] }} {{ $row['balance_due'] }}</td>
                    @if($reportsShowVat ?? false)
                        <td class="text-end">{{ $row['currency'] }} {{ $row['tax_for_row'] }}</td>
                    @endif
                </tr>
            @endforeach
            </tbody>
        </table>

        <p class="muted" style="font-size: 10px; margin-top: 8px;">Table columns Paid / Credit are per guest-night; summary above shows period totals.</p>
    @else
        <p class="muted">No in-house accommodations found for this period.</p>
    @endif

    <div class="signature-block">
        <div class="sig-col">
            <div class="sig-heading">Prepared by</div>
            <div class="sig-field">
                <div class="sig-label">Name</div>
                <div class="sig-line"></div>
            </div>
            <div class="sig-field">
                <div class="sig-label">Signature</div>
                <div class="sig-line"></div>
            </div>
        </div>
        <div class="sig-col">
            <div class="sig-heading">Verified by</div>
            <div class="sig-field">
                <div class="sig-label">Name</div>
                <div class="sig-line"></div>
            </div>
            <div class="sig-field">
                <div class="sig-label">Signature</div>
                <div class="sig-line"></div>
            </div>
        </div>
        <div class="sig-col">
            <div class="sig-heading">Approved by</div>
            <div class="sig-field">
                <div class="sig-label">Name</div>
                <div class="sig-line"></div>
            </div>
            <div class="sig-field">
                <div class="sig-label">Signature</div>
                <div class="sig-line"></div>
            </div>
        </div>
    </div>

    <script>
        window.onload = function() { window.print(); };
    </script>
</body>
</html>
